// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQkRmpCCDTHO3-Upw7VnRy7mwqnWyNNxo',
    appId: '1:291088983781:web:7cfd846d343deb60f4960c',
    messagingSenderId: '291088983781',
    projectId: 'scan-and-pay-guihzm',
    authDomain: 'scan-and-pay-guihzm.firebaseapp.com',
    storageBucket: 'scan-and-pay-guihzm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDChy06CAi6YkcSbpELoeA66JfdO4kTbGI',
    appId: '1:291088983781:android:4d27b5b1bcfbdf6bf4960c',
    messagingSenderId: '291088983781',
    projectId: 'scan-and-pay-guihzm',
    storageBucket: 'scan-and-pay-guihzm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDChy06CAi6YkcSbpELoeA66JfdO4kTbGI',
    appId: '1:291088983781:ios:b39e16066519db5ff4960c',
    messagingSenderId: '291088983781',
    projectId: 'scan-and-pay-guihzm',
    storageBucket: 'scan-and-pay-guihzm.firebasestorage.app',
  );
}