// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const _webApiKey = String.fromEnvironment(
    'FIREBASE_API_KEY_WEB',
    defaultValue: 'FIREBASE_API_KEY_WEB_TEST',
  );

  static const _mobileApiKey = String.fromEnvironment(
    'FIREBASE_API_KEY_MOBILE',
    defaultValue: 'FIREBASE_API_KEY_MOBILE',
  );

  static const _webAppId = String.fromEnvironment(
    'FIREBASE_WEB_APP_ID',
    defaultValue: '1:291088983781:web:7cfd846d343deb60f4960c',
  );

  static const _androidAppId = String.fromEnvironment(
    'FIREBASE_ANDROID_APP_ID',
    defaultValue: '1:291088983781:android:4d27b5b1bcfbdf6bf4960c',
  );

  static const _iosAppId = String.fromEnvironment(
    'FIREBASE_IOS_APP_ID',
    defaultValue: '1:291088983781:ios:b39e16066519db5ff4960c',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: _webAppId,
    messagingSenderId: '291088983781',
    projectId: 'scan-and-pay-guihzm',
    authDomain: 'scan-and-pay-guihzm.firebaseapp.com',
    storageBucket: 'scan-and-pay-guihzm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _mobileApiKey,
    appId: _androidAppId,
    messagingSenderId: '291088983781',
    projectId: 'scan-and-pay-guihzm',
    storageBucket: 'scan-and-pay-guihzm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _mobileApiKey,
    appId: _iosAppId,
    messagingSenderId: '291088983781',
    projectId: 'scan-and-pay-guihzm',
    storageBucket: 'scan-and-pay-guihzm.firebasestorage.app',
  );
}
